### ISSUE TITLE
[joss review] Statements of need

### ISSUE THREAD

**Issue by zpace** [biboyd/SALSA#3]
Hi @biboyd, I'm reviewing the SALSA paper submission to JOSS, and I would like to suggest slightly expanding your Statements of Need in both the paper submission and the public RTD documentation. I think the text in your README's second paragraph about allowing comparisons between models and observations is very good, and would go a long way in clarifying who the target user is and what their use cases might be.

**Comment by biboyd** [comment]
Hi, I added to the "statement of need" in both places. Tried to put more stress on the ability to compare. I also rearranged the paper just slightly so that the "statement of need" section was more focused with the rest going to the summary.

**Comment by zpace** [comment]
referencing https://github.com/openjournals/joss-reviews/issues/2581
