### ISSUE TITLE
[joss review] add gcc to dependencies

### ISSUE THREAD

**Issue by zpace** [biboyd/SALSA#4]
JOSS reviewer here, again. By chance, I tried to install SALSA on a relatively clean machine which evidently didn't have gcc installed. Conda & pip just complained at me, and while the issue was easy to diagnose & fix, I would recommend adding gcc to the formal requirements.

**Comment by biboyd** [comment]
I added a note in the install documentation as well as in the README to warn people they need gcc.

I also left comments in the `environment.yml` file and `setup.py` file to alert people as well.

**Comment by zpace** [comment]
referencing https://github.com/openjournals/joss-reviews/issues/2581
